# Generated by Django 4.2.9 on 2025-02-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
