# Generated by Django 4.2.9 on 2025-02-18 12:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, verbose_name='Cidade')),
                ('state', models.CharField(max_length=150, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Epidemiological_weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se', models.CharField(max_length=150, verbose_name='SE (semana epidemiologica)')),
                ('year', models.IntegerField(verbose_name='ano')),
            ],
            options={
                'verbose_name': 'Semana Epidemiologicas',
                'verbose_name_plural': 'Semana Epidemiologicas',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Hospital')),
                ('specialty', models.CharField(max_length=150, verbose_name='Especialidade do Hospital')),
                ('location', models.CharField(max_length=150, verbose_name='Localização do Hospital')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitais',
            },
        ),
        migrations.CreateModel(
            name='Hospitalization_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, max_length=150, null=True, verbose_name='dados das internações')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Internações por dia',
                'verbose_name_plural': 'Internações por dia',
            },
        ),
        migrations.CreateModel(
            name='Illnesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Doença')),
                ('degree_risk', models.IntegerField(choices=[(0, 'Baixa'), (1, 'Média'), (2, 'Alta')], default=0, verbose_name='Grau de risco')),
            ],
            options={
                'verbose_name': 'Doença',
                'verbose_name_plural': 'Doenças',
            },
        ),
        migrations.CreateModel(
            name='Quantity_hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inserido em')),
                ('clinic_UTI', models.CharField(choices=[('Clinica', 'Clinica'), ('UTI', 'UTI')], default=0, max_length=150, verbose_name='Tipo de internação')),
                ('t0_to_28_days_male', models.IntegerField(default=0, verbose_name='Homem de 0 a 28 dias')),
                ('t0_to_28_days_female', models.IntegerField(default=0, verbose_name='Mulher de 0 a 28 dias')),
                ('t29d_to_1y_male', models.IntegerField(default=0, verbose_name='Homem de 29 dias a 1 ano')),
                ('t29d_to_1y_female', models.IntegerField(default=0, verbose_name='Mulher de 29 dias a 1 ano')),
                ('t1y_to_5y_male', models.IntegerField(default=0, verbose_name='Homem de 1 a 5 anos')),
                ('t1y_to_5y_female', models.IntegerField(default=0, verbose_name='Mulher de 1 a 5 anos')),
                ('t6y_to_10y_male', models.IntegerField(default=0, verbose_name='Homem de 6 a 10 anos')),
                ('t6y_to_10y_female', models.IntegerField(default=0, verbose_name='Mulher de 6 a 10 anos')),
                ('t11y_to_17y_male', models.IntegerField(default=0, verbose_name='Total do dia')),
                ('t11y_to_17y_female', models.IntegerField(default=0, verbose_name='Total do dia')),
                ('adult_male', models.IntegerField(default=0, verbose_name='Total do dia')),
                ('adult_female', models.IntegerField(default=0, verbose_name='Total do dia')),
                ('old_male', models.IntegerField(default=0, verbose_name='Total do dia')),
                ('old_female', models.IntegerField(default=0, verbose_name='Total do dia')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospital', verbose_name='Hospital')),
                ('internacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospitalization_information', verbose_name='internação')),
            ],
            options={
                'verbose_name': 'Quantidade por hospital',
                'verbose_name_plural': 'Quantidade por hospitais',
            },
        ),
        migrations.AddField(
            model_name='hospitalization_information',
            name='illnesses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.illnesses', verbose_name='Doença'),
        ),
        migrations.AddField(
            model_name='hospitalization_information',
            name='se',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.epidemiological_weeks', verbose_name='SE'),
        ),
    ]
