# Generated by Django 4.2.9 on 2025-02-21 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization_information',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='quantity_hospital',
            name='adult_female',
            field=models.IntegerField(default=0, verbose_name='Mulher Adulta'),
        ),
        migrations.AlterField(
            model_name='quantity_hospital',
            name='adult_male',
            field=models.IntegerField(default=0, verbose_name='Homem Adulto'),
        ),
        migrations.AlterField(
            model_name='quantity_hospital',
            name='old_female',
            field=models.IntegerField(default=0, verbose_name='Mulher Idosa'),
        ),
        migrations.AlterField(
            model_name='quantity_hospital',
            name='old_male',
            field=models.IntegerField(default=0, verbose_name='Homem Idoso'),
        ),
        migrations.AlterField(
            model_name='quantity_hospital',
            name='t11y_to_17y_female',
            field=models.IntegerField(default=0, verbose_name='Mulher de 11 a 17 anos'),
        ),
        migrations.AlterField(
            model_name='quantity_hospital',
            name='t11y_to_17y_male',
            field=models.IntegerField(default=0, verbose_name='Homem de 11 a 17 anos'),
        ),
    ]
